name: "Create issue with parameters"
description: "Creates GH Issue with parameter values defined in inputs"

inputs:
    repository:
      description: Github repository where action to be created
      type: string
      required: true
      default: '.'
    access_token:
      description: Github token to use while creating the issue in remote repository. Pass PAT existing oin remote repository
      required: true
    title:
      description: Title to be configured for the issue
      type: string
      required: true
    body:
      description: Body to be configured for the issue
      type: string
      required: true
    labels:
      description: A list of labels to be configured for the issue (coma separated list of existing labels in the target repository)
      type: string
      required: true

runs:
  using: "composite"
  steps:
    - name: Prepare environment
      shell: bash
      run: |
        repo=''
        if [ "${{ inputs.repository }}" != "." ]; 
        then 
          repo="--repo ${{ inputs.repository }}";
        fi
        echo "repo=$repo" >> $GITHUB_ENV
    - name: Create GH Issue
      run: gh issue create --title "${{ inputs.title }}" --label "${{ inputs.labels }}" --body "${{ inputs.body }}" $repo
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.access_token }}
